services:
  mongodb:
    restart: unless-stopped
    container_name: nonogram-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
      MONGO_INITDB_DATABASE: $DB_NAME
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - nonogram_network

  api:
    restart: unless-stopped
    container_name: nonogram-api
    build: ./api
    image: nonogram-api
    depends_on:
      - mongodb
    ports:
      - "3050:3050"
    environment:
      - API_PORT=$API_PORT
      - JWT_SECRET=$JWT_SECRET
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
    networks:
      - nonogram_network

  app:
    restart: unless-stopped
    container_name: nonogram-app
    build: ./app
    image: nonogram-app
    depends_on:
      - api
    ports:
      - 8080:8080
    networks:
      - nonogram_network

volumes:
  mongo_data:
  mongo_config:

networks:
  nonogram_network:
