services:
  mongo:
    container_name: nonogram-mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASS
      MONGO_INITDB_DATABASE: $MONGODB_DBNAME
    ports:
      - "27017:27017"
    volumes:
      # - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-config:/data/configdb
      - mongo-data:/data/db
    networks:
      - nonogram-network
    
  api:
    container_name: nonogram-api
    build: ./api
    image: nonogram-api
    depends_on:
      - mongo
    ports:
      - "3050:3050"
    env_file:
      - .env
    networks:
      - nonogram-network

  app: 
    container_name: nonogram-app
    build: ./app
    image: nonogram-app
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - nonogram-network
    
volumes:
  mongo-data:
  mongo-config:

networks:
  nonogram-network:
